Raise if a rule contains whitespace
liveview-native/live_view_native_stylesheet pull request #47
Opened 2024-01-21 09:22 UTC by NduatiK

- Add regression test for new behaviour
- Improve readability of existing error reporting tests

2024-01-21 16:44 UTC, bcardarella requested changes

2024-01-21 16:44 UTC, bcardarella commented on test/sheet_parser_test.exs
> +    test "raises compile error when block header is incorrect (1)" do
what separates the two test cases here between (1) and (2)? That different should be in the test name so others reading the case can know. If there is no different then it should be consolidated into a single test case.

2024-01-24 08:06 UTC, NduatiK commented on test/sheet_parser_test.exs
> +    test "raises compile error when block header is incorrect (1)" do
I've clarified the distinction

2024-01-26 00:25 UTC, bcardarella approved these changes

2024-01-26 00:25 UTC, merged